In [1]:
import numpy as np
np.__version__

'1.21.5'

## 1. 1차원 배열

In [6]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape) # a1이 어떤 모양을 가지고 있냐. (5, ) 5개의 값을 가진 1차원 배열이구나.
print(a1[0], a1[1],a1[2],a1[3],a1[4])
a1[0] = 4 # 리스트처럼 이렇게 수정이 가능하다.
a1[1] = 5 # 리스트처럼 이렇게 접근이 가능하다.
a1[2] = 6
print(a1) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [9]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape) # 3개의 항과 3개의 열을 가진 2차원 배열
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [12]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
             [[1,2,3], [4,5,6], [7,8,9]],
             [[1,2,3], [4,5,6], [7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


In [133]:
a = [1, 2, 3, 4, 5, 10, 20, "가", "나"] #배열이 아니라 리스트
print(a)
print(type(a))

[1, 2, 3, 4, 5, 10, 20, '가', '나']
<class 'list'>


In [134]:
a = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"]) #콤마가 없고 모두 같은 형식으로 묶어준다 #이것이 배열
print(a)
print(type(a)) # <class 'numpy.ndarray'>가 있어서 배열을 쉽게 쓸 수 있다. nd = n dimension = 다차원
print(a.shape) # (9,) = 1차원에 9개의 값이 있다, 2차원이 존재하지 않는다
print(a.ndim)  # 1 = 1차원
print(a.dtype) # U = Unicode / 유니코드로 11바이트


['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
1
<U11


In [135]:
a = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"]) # 기본
print(a)

a = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"], dtype = int) # 정수형으로 타입설정
print(a)

a = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"], dtype = float) # 실수형으로 타입 설정 # 소숫점
print(a)

['1' '2' '3' '4' '5' '10' '20' '30' '40']
[ 1  2  3  4  5 10 20 30 40]
[ 1.  2.  3.  4.  5. 10. 20. 30. 40.]


### (1) 벡터화 연산

    - 1차원 배열 : 벡터
    - 2차원 배열 : 매트릭스
    

In [4]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a*2) # 연산이 아니라 반복
#print(a-2) #연산이 안된다

b = np.array(a) # 배열로 바꿔주었다
print(b*2) # 연산이 되었다
print(b-2) # 연산이 되었다
print(b+2) # 각 값에 +2가 되었다

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]
[-2 -1  0  1  2  3  4  5  6  7]
[ 2  3  4  5  6  7  8  9 10 11]


### (2) 인덱스 접근

In [5]:
print(b[0], b[1])

0 1


## 2. 2차원 배열

In [138]:
a =np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape) 
print(a.ndim) # 2차원
print(a.dtype) #정수형

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


### (1) 인덱스 접근

In [139]:
a =np.array([[1,2,3], [4,5,6]])

print(a[0]) # 배열
print(a[1])

print(a[0][0], a[0][1])
print(a[0, 0])
print(a[0, 0], a[0][1])

print("-------------------------------------------------------------")

b = [[1,2,3], [4,5,6]] # 리스트
print(b[0][0], b[0][1])
# print(b[0, 0], b[0, 1]) # 이렇게하면 안되더라

print("-------------------------------------------------------------")

print(len(a)) # 배열 a의 길이는? (값이 몇개냐)
print(len(a[0])) # 배열 a의 첫번째 값의 길이는?

[1 2 3]
[4 5 6]
1 2
1
1 2
-------------------------------------------------------------
1 2
-------------------------------------------------------------
2
3


## 3. 3차원 배열

In [140]:
a = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])

print(a)
print(a.shape) 
print(a.ndim) # 3차원
print(a.dtype) 

print(len(a)) 
print(len(a[0]))
print(len(a[0][0]))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
3
int32
2
2
4


In [141]:
a = np.array(1)
print(a)
print(a.shape)
print(a.ndim) # 0차원, 그냥 상수 하나

print("-------------------------------------------------------------")

a = np.array([1])
print(a)
print(a.shape)
print(a.ndim) # 1차원

print("-------------------------------------------------------------")

a = np.array([[1]])
print(a)
print(a.shape)
print(a.ndim) # 2차원

print("-------------------------------------------------------------")

a = np.array([[[1]]])
print(a)
print(a.shape)
print(a.ndim) # 3차원

1
()
0
-------------------------------------------------------------
[1]
(1,)
1
-------------------------------------------------------------
[[1]]
(1, 1)
2
-------------------------------------------------------------
[[[1]]]
(1, 1, 1)
3


## 4. 집계함수



In [6]:
x = np.random.randn(8)
print(x)
y = np.random.randn(8)
print(y)

[-1.2879723  -0.91856303 -0.51429235  0.15960966 -0.6338543  -0.04804303
 -0.44528691  0.5148994 ]
[-0.61125188 -1.08535642  2.1166781  -0.49657413 -0.71200577 -1.2852939
  0.70867722  0.63144384]


In [ ]:
np.maximum(x, y) # 같은 위치의 x와 y값 중에서 가장 높은 값을 가져옴

In [ ]:
arr = np.random.randn(5, 4)
print(arr)

In [ ]:
?np.random.randn

In [ ]:
print(arr.sum())
print(arr.sum(axis=0)) # 보통 0의 값이 열로 사용됨
print(arr.sum(axis=1))

In [ ]:
?np.sum

## 5. 배열의 인덱싱

In [17]:
arr = np.array([0, 1, 2, 3, 4])

print(arr[2], arr[3], arr[-1], arr[-3])

2 3 4 2


In [3]:
arr = np.array([i for i in range(10)]) # list comprehension도 사용가능!

print(arr)

idx = np.array([True, False,True, False,True, False,True, False,True, False]) # 참, 거짓

print(arr[idx])
print(arr[arr%2 == 0]) #list에서는 안되지만, 배열이라서 가능

# arr에서 3의 배수를 찾아라
print(arr[arr%3 == 0])

# arr에서 4로 나누면 1이 남는 수를 찾아라
print(arr[arr%4 == 1])

#arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라

print(arr[(arr % 3 == 0) & (arr % 4 == 1)]) # and 대신 &를 써준다.



[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


In [20]:
#arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라 - 강사님 버전

#print(arr[arr % 3 == 0 & arr % 4 ==1]) #이렇게 묶는게 아니라 아래처럼 묶자
print(arr[(arr % 3 == 0) & (arr % 4 ==1)]) # 이게 정답 # 여러개의 조건문을 묶을 때는 괄호로 묶어주자

[9]


### 배열의 슬라이싱
- 슬라이싱 구문 : a[start:stop:step]
- 기본값: start=0, stop=ndim, step=1

In [44]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [47]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1]) # 역순으로
print(a2[::-1, ::-1]) # 행렬 전체 역순으로

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [155]:
arr = np.array([[0,1,2,3],
                [4,5,6,7],
                [8,9,10,11]])

print(arr[0, 0:2]) # 0번째 행의 2번째 열까지

print("-------------------------------------------------------------")

print(arr[1:3, 0:2]) # 1번째 행에서 3번째 행까지, 0번째 0에서 2번째열까지

print("-------------------------------------------------------------")

print(arr[0, :])

print("-------------------------------------------------------------")

print(arr[[2, 1, 0], :])

print("-------------------------------------------------------------")

print(arr[:, [1, 2]])

[0 1]
-------------------------------------------------------------
[[4 5]
 [8 9]]
-------------------------------------------------------------
[0 1 2 3]
-------------------------------------------------------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
-------------------------------------------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]


### 불리언 인덱싱

In [51]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi]) # True에 해당하는 값만 출력이 된다

b1 = [True, False, True, True, False]
print(a1[b1])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [52]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True  True False]
 [ True False False]]
[1 2 3 4 5 7]


### 팬시 인덱싱(Fancy Indexing)

In [54]:
print(a1)
print([a1[0], a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1], [2,0]]) # 2차원 배열을 인덱스로 잡아주니 결과값도 2차원으로 나왔다.
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [56]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col]) # row의 첫번째 값 0과 col의 첫번째 값 1을 통해서 0번째 열, 1번째 값 = 2
# row의 2번째 값 2와 col의 2번째 값 2를 통해서 2번째 열, 2번째 값 = 9
print(a2[row, :])
print(a2[:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 7. numpy 자료형

- b : 불리언
- i : 정수형
- u : 부호없는 정수형(양수만 쓸거다) (unsigned)
- f : 부동 소수점
- c : 복소수
- O : 객체 (Object)
- S : 바이트 문자열, 아스키코드, 영어만 쓸거라면 S
- U : 유니코드 문자열, 영어 외 다른 문자도 쓸거라면 U


In [ ]:
arr = np.array([1, 2, 3], dtype = "f") # defualt값이 32
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3], dtype = np.float16) # 직접 지정해주고 싶다면 이렇게!
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3], dtype = "S")
print(arr) # dtype = "S"에서는 값 앞에 b가 붙는데 이는 Byte를 나타낸다. 1바이트임을 알 수 있음.
print(arr.dtype)
print(arr[0]+arr[1])
print(arr[0]+arr[1]+arr[2])

arr = np.array([1, 2, 3], dtype = "U") # 유니코드로 바꿨더니 B 표시가 사라짐
print(arr) 
print(arr.dtype)
print(arr[0]+arr[1])
print(arr[0]+arr[1]+arr[2])

## 8. 배열 생성

### zeros()
 - 모든 요소를 0으로 초기화

In [162]:
np.zeros(5) # 따로 지정하지 않으면 실수형(float)


print("-------------------------------------------------------------")

arr = np.zeros(5, dtype="i8")
print(arr)
print(arr.dtype)

print("-------------------------------------------------------------")

arr = np.zeros(5, dtype="U4") # 4글자까지 쓰게 하겠다.
print(arr)
print(arr.dtype)
arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde" # 5글자는 아무것도 안쓰인 상태로 나왔다.
print(arr)

print("-------------------------------------------------------------")

print(np.zeros((2, 3)))

-------------------------------------------------------------
[0 0 0 0 0]
int64
-------------------------------------------------------------
['' '' '' '' '']
<U4
['abc' 'abcd' 'abcd' '' '']
-------------------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


### ones 
- 모든 요소를 1로 초기화

In [163]:
arr = np.ones((2, 3, 4))
print(arr)

print("-------------------------------------------------------------")

arr1 = np.zeros((2,3)) # 0으로 배열을 만들자
print(arr1)
arr2 = np.ones_like(arr1) # arr1을 만들었지만 0이 아니라 1로 바꾸고 싶다
print(arr2)

print("-------------------------------------------------------------")



[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-------------------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
-------------------------------------------------------------


### full()
- 모든 요소를 지정한 값으로 초기화

In [13]:
full1 = np.full((3,3), 1.31)
print(full1)

[[1.31 1.31 1.31]
 [1.31 1.31 1.31]
 [1.31 1.31 1.31]]


### eye()
- 단위행렬(identity matrix) 생성
- 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### empty()
- 초기화되지 않은 배열 생성
- 초기화가 없어서 배열 생성비용 저렴하고 빠름
- 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [16]:
arr3 = np.empty((4,3)) #비워두겠다 -> 채우지않겠다 -> 메모리에 있던 값을 그대로 가져온다 -> 가비지값이 나온다
print(arr3)

np.empty(10)

[[1.27734575e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.14587773e-312 1.58817677e-052]
 [7.12060217e-091 5.93736762e-038 3.54811976e-062]
 [2.46406370e+184 3.99910963e+252 1.90979636e-312]]


array([1.27734575e-311, 2.47032823e-322, 1.14587773e-312, 1.58817677e-052,
       7.12060217e-091, 5.93736762e-038, 3.54811976e-062, 2.46406370e+184,
       3.99910963e+252, 1.90979636e-312])

### _like()
- 지정된 배열과 shape가 같은 행렬 생성
- np.zeros_like()
- np.ones_like()
- np.full_like()
- np.empty_like()

In [23]:
print(a1)
np.zeros_like(a1) # a1과 같은 배열의 0으로 채워진(zeros) 배열을 만들어줘
np.ones_like(a2) # a2와 같은 배열에 1으로 채워진(ones) 배열을 만들어줘
np.full_like(a3, 10) # a3와 같은 배열모양에 10으로 꽉 채워진 배열을 만들어줘

[4 5 6 4 5]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### arange()
- 정수 범위로 배열 생성

In [26]:
np.arange(0, 30, 2) # 0 ~ 30까지 2의 간격으로 배열을 만들어줘

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### linspace()
- 범위 내에서 균등 간격의 배열 생성

In [28]:
np.linspace(0, 1, 5) # 0 에서 1까지 총 갯수가 5가 되도록 균등한 간격으로 배열을 만들어줘(첫시작0과 끝나는1포함 5개)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### logspace()
- 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [29]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [24]:
arr3 = np.empty((4,3)) #비워두겠다 -> 채우지않겠다 -> 메모리에 있던 값을 그대로 가져온다 -> 가비지값이 나온다
print(arr3)

print("-------------------------------------------------------------")

arr = np.arange(10) # arange = 배열로 만듬 , range = 리스트로 만들어줌
print(arr)

arr = np.linspace(0, 100, 5) # x축의 값을 채울 때 간간히 쓰인다
print(arr)
arr2 = np.linspace(0, 100, 10) # 값1과 값2 사이의 값을 균등한 간격으로 떨어진 10개를 뽑아온다.
print(arr2)



[[1.27734575e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.14587773e-312 1.58817677e-052]
 [7.12060217e-091 5.93736762e-038 3.54811976e-062]
 [2.46406370e+184 3.99910963e+252 1.90979636e-312]]
-------------------------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
[  0.  25.  50.  75. 100.]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### 날짜 

In [36]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [37]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [38]:
datetime = np.datetime64('2020-06-01 12:00')
datetime
                         

numpy.datetime64('2020-06-01T12:00')

In [39]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') # 'ns' 나노 초
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

## 9. 전치 연산(Transpose)

In [91]:
print(a2)
print(a2.T) # 대각선으로는 그대로고 행과 열이 바뀌었다. 

[[1 0 3]
 [1 0 0]
 [7 8 9]]
[[1 1 7]
 [0 0 8]
 [3 0 9]]


In [92]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [94]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 3]
 [1 0 0]
 [7 8 9]]
[[1 1 7]
 [0 0 8]
 [3 0 9]]


In [95]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]



## 10. 배열의 크기 변경

- reshape() # 배열의 형상을 변경
- flatten()
- ravel()

In [153]:
arr = np.arange(12)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [154]:
arr1 = arr.reshape(3, 4)
print(arr1)
print(arr1.shape)

print("-------------------------------------------")

arr1 = arr.reshape(3, -1) # 앞쪽에 몇행으로 나눌지만 지정한다음, -1을 적어두면 자동으로 계산된다
print(arr1)               # 데이터가 쌓여서 직접 계산하지 못할 정도의 수량이라면 -1을 꼭 생각하자
print(arr1.shape)          # -1 : 인덱스에서 마지막 위치, find에서 위치가 없다, 배열크기변경에서 열의 자동계산

print("-------------------------------------------")


arr1 = arr.reshape(-1, 4) # 뒤쪽에 몇열으로 나눌지만 지정한다음, -1을 적어두면 자동으로 계산된다
print(arr1)               # 데이터가 쌓여서 직접 계산하지 못할 정도의 수량이라면 -1을 꼭 생각하자
print(arr1.shape)          # -1 : 인덱스에서 마지막 위치, find에서 위치가 없다, 배열크기변경에서 행렬의 자동계산


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
-------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
-------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
arr2 = arr.reshape(2,2,3)                              # -1의 효율성
print(arr2)
print(arr2.shape)

print("-------------------------------------------")

arr2 = arr.reshape(2,2,-1)
print(arr2)
print(arr2.shape)

print("-------------------------------------------")

arr2 = arr.reshape(2,-1,3)
print(arr2)
print(arr2.shape)

print("-------------------------------------------")

arr2 = arr.reshape(-1,2,3)
print(arr2)
print(arr2.shape)

In [ ]:
print(arr1.reshape(12))
print(arr1.flatten()) # 1차원으로 바꿔주는 플레튼
print(arr1.ravel()) # 1차원으로 바꿔주는 레이블??

In [ ]:
print(arr2.reshape(12))
print(arr2.flatten())
print(arr2.ravel())

### newaxis() : 새로운 축 추가

In [99]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [101]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[6 1 3 5 8]
 [4 6 3 9 2]]
[[6 1]
 [3 5]
 [8 4]
 [6 3]
 [9 2]]


In [102]:
n2.resize((5, 5))  # 배열 크기 증가, 남은 공간은 0으로 채워짐
print(n2) 

[[6 1 3 5 8]
 [4 6 3 9 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [103]:
n2.resize((3,3))
print(n2) # 배열을 줄였을 떄, 포함되지 못한 값은 삭제된다.

[[6 1 3]
 [5 8 4]
 [6 3 9]]


### 배열값 삽입
- insert() : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [61]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1) # b1은 a1의 0번쨰 자리에 10이라는 값을 넣은 배열이다
print(a1) # a1은 그대로다
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [64]:
print(a2)
b2 = np.insert(a2, 1, 10, axis = 0)
print(b2)
c2 = np.insert(a2, 1, 10, axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정
- 배열의 인덱싱으로 접근하여 값 수정

In [66]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]


In [69]:
i = np.array([1,3,4])
a1[i] = 0 # 팬시 인덱싱
print(a1) # i번에 위치한 값을 모두 0으로 바꿔라
a1[i] += 4 # i번에 위치한 값을 모두 +4를 해라
print(a1)

[9 0 3 0 0]
[9 4 3 4 4]


In [78]:
a2 = np.arange(1, 10, 1)
print(a2)
a2 = a2.reshape(3,3)
print(a2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[1] = 1
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [1 1 1]
 [7 8 3]]


In [81]:
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [1 1 9]
 [7 8 9]]
[[1 0 3]
 [1 1 0]
 [7 8 9]]


### 배열 값 삭제
- delete() : 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [82]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [83]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)

[[1 0 3]
 [1 1 0]
 [7 8 9]]
[[1 0 3]
 [7 8 9]]


### 배열 복사
- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님
- 원본에도 영향을 준다
- 동일한 메모리에 위치하기에

In [85]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 3]
 [1 1 0]
 [7 8 9]]
[[1 0]
 [1 1]]
[[1 0]
 [1 1]]
[[1 0]
 [1 0]]
[[1 0 3]
 [1 0 0]
 [7 8 9]]


In [88]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2) # copy를 사용한 녀석의 값을 바꿨음에도 복사본이기에 원본에는 영향을 주지 않는다.

[[1 0 3]
 [1 0 0]
 [7 8 9]]
[[1 0]
 [1 0]]
[[1 1]
 [1 1]]
[[1 0 3]
 [1 0 0]
 [7 8 9]]


### 배열 추가
- append() : 배열의 끝에 값 추가

In [104]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [105]:
c2 = np.append(a2, b2) # axis 지정이 없으면 1차원 배열 형태로 변형되어 결합
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [106]:
c2 = np.append(a2, b2, axis = 0) # axis를 0으로 지정 # shape[0]을 제외한 나머지 shape는 같아야 함
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [107]:
c2 = np.append(a2, b2, axis = 1) # axis를 1로 지정 # shape[1]을 제외한 나머지 shape는 같아야 함
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 11. 배열의 연결(병합)

- hstack(), vstack() #hstack : horizon stack 수평   #vstack : vertical stack 수직
- concatenate()
- dstack(), stack()
- tile()

### (1) hstack(), vstack()

### vstack() : 수직 스택(vertical stack), 1차원으로 연결

In [119]:
a2 = np.array([[1,2,3],[4,5,6]])
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### hstack() : 수평 스택(horizontal stack), 2차원으로 연결

In [120]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### dstack() : 깊이 스택(depth stack), 3차원으로 연결

In [121]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

### stack() : 새로운 차원으로 연결

In [122]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [8]:
#### 1차원 배열

a = np.random.randint(0, 10, (4)) # 정수의 범위 중 0에서 10까지, 그리고 4개를 뽑겠다
print(a)

# ?np.random.randint

b = np.ones(4, dtype="i")
print(b)


print("---------------------------------------")

print(np.vstack([a,b])) # 묶고싶은 배열들을 리스트로 묶어서 넣어준다
# 수직으로 합쳐져서 1차원 2개가 2차원 1개로 묶였다
print("---------------------------------------")

print(np.hstack([a,b])) # 1차원 옆에 가로로 1차원이 묶였다
print("---------------------------------------")
print("---------------------------------------")
print("---------------------------------------")

#### 크기가 다를경우

a = np.random.randint(0, 10, (4)) # 정수의 범위 중 0에서 10까지, 그리고 4개를 뽑겠다
print(a)

?np.random.randint

b = np.ones(5, dtype="i")
print(b)


print("---------------------------------------")
print(np.hstack([a,b])) # 크기가 다르지만 1차원 옆에 가로로 1차원이 묶였다

#print(np.vstack([a,b])) # 크기가 다르니까 묶이지 못했다
print("---------------------------------------")



[0 2 0 4]
[1 1 1 1]
---------------------------------------
[[0 2 0 4]
 [1 1 1 1]]
---------------------------------------
[0 2 0 4 1 1 1 1]
---------------------------------------
---------------------------------------
---------------------------------------
[0 0 7 2]
[1 1 1 1 1]
---------------------------------------
[0 0 7 2 1 1 1 1 1]
---------------------------------------


In [ ]:
##### 2차원 배열

a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4))
print(a, b)

print("---------------------------------------")

print(np.vstack([a,b]))

print("---------------------------------------")

print(np.hstack([a,b]))

### (2) concatenate

- concatenate 메소드는 선택한 축(axis)의 방향으로 배열을 연결해주는 메소드입니다. concatenate 는 '사슬 같이 연결하다'는 의미입니다.
- 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [108]:
#### 1차원 배열

a = np.random.randint(0, 10, (4)) # 정수의 범위 중 0에서 10까지, 그리고 4개를 뽑겠다
print(a)

b = np.ones(5, dtype="i")
print(b)


print("---------------------------------------")
print(np.concatenate([a,b])) # 1차원 배열에서 hstack과 .concatenate는 결과가 똑같다

print("---------------------------------------")


[0 4 2 4]
[1 1 1 1 1]
---------------------------------------
[0 4 2 4 1 1 1 1 1]
---------------------------------------


In [117]:
g = np.random.randint(0, 10, (3, 5))
print(g)

[[8 6 5 1 7]
 [4 3 6 1 4]
 [0 8 5 4 2]]


In [111]:

##### 2차원 배열

a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4))
print(a)
print("---------------------------------------")
print(b)
print("---------------------------------------")
print(a, b)

print("---------------------------------------")

print(np.concatenate([a,b], axis=0)) # axis = 0 , 디폴트값이라 생략되어 있음
# ?np.concatenate

print("---------------------------------------")
                                      # 2차원 배열의 경우 axis는 0,1이고 3차원은 0,1,2, 4차원은0,1,2,3이지만
                                     # 몇차원인지 모를 경우에 -1로 하면 그냥 가장 마지막 축값.
print(np.concatenate([a,b], axis=1)) # axis = 1, 로 바꿨더니 합쳐지는 행과 렬이 바뀌었다.
print("---------------------------------------")
print(np.concatenate([a,b], axis=-1)) # -1인 경우 가장 마지막값이라고 생각



[[2 9 6 5]]
---------------------------------------
[[6 6 6 3]]
---------------------------------------
[[2 9 6 5]] [[6 6 6 3]]
---------------------------------------
[[2 9 6 5]
 [6 6 6 3]]
---------------------------------------
[[2 9 6 5 6 6 6 3]]
---------------------------------------
[[2 9 6 5 6 6 6 3]]


In [ ]:

print("---------------------------------------")
print("------------사이즈가 다를 경우 --------")
print("---------------------------------------")

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, 2))
print(a)
print("---------------------------------------")
print(b)
print("---------------------------------------")
print(a, b)
print("---------------------------------------")
print("---------------------------------------")

#print(np.concatenate([a,b], axis=0)) #얘는 안된다.
print(np.concatenate([a,b], axis=1))


print("---------------------------------------")
print("------------사이즈가 다를 경우 --------")
print("---------------------------------------")


In [ ]:
#### 3차원 배열

a = np.random.randint(0, 10, (4, 2, 3))
b = np.random.randint(0, 10, (5, 2, 3))
print(a)
print(a.shape)
print("---------------------------------------")
print(b)
print(b.shape)
print("---------------------------------------")
print(a, b)
print("---------------------------------------")

c = np.concatenate([a,b], axis = 0)
print(c)
print(c.shape)

# d = np.concatenate([a,b], axis = 1) # 얘는 행이 달라서 안되더라

# e = np.concatenate([a,b], axis = 2) # 얘도 안되더라

In [ ]:
#### 3차원 배열 테스트

a = np.random.randint(0, 10, (4, 2, 3))
b = np.random.randint(0, 10, (4, 2, 4))
print(a)
print(a.shape)
print("---------------------------------------")
print(b)
print(b.shape)
print("---------------------------------------")
print(a, b)
print("---------------------------------------")

#c = np.concatenate([a,b], axis = 0)
#print(c)
#print(c.shape)

#d = np.concatenate([a,b], axis = 1) # 얘는 행이 달라서 안되더라

e = np.concatenate([a,b], axis = 2) # 마지막이 다르니까 얘만 되더라
print(e)
print(e.shape)

## (3) stack(), dstack()

In [ ]:
a1 = np.ones((3,4))
a2 = np.zeros((3,4))

a3 = np.stack([a1, a2])
print(a1.shape)
print(a2.shape)
print("---------------------------------------")
print(a1)
print("---------------------------------------")
print(a2)
print("---------------------------------------")
print(a3.shape)
print("---------------------------------------")
print("------ 축을 바꿔 보자 axis = 0 --------")
print("---------------------------------------")


a4 = np.stack([a1,a2], axis = 0) 
print(a4)
print(a4.shape)
print("---------------------------------------")
print("------ 축을 바꿔 보자 axis = 1 --------")
print("---------------------------------------")
a4 = np.stack([a1,a2], axis = 1) 
print(a4)
print(a4.shape)
print("---------------------------------------")
print("------ 축을 바꿔 보자 axis = 2 --------")
print("---------------------------------------")
a4 = np.stack([a1,a2], axis = 2) # dstack()
print(a4)
print(a4.shape)

In [ ]:
a1 = np.ones((3,4))
a2 = np.zeros((3,4))

a3 = np.dstack([a1, a2]) #스택의 깊이를 기준으로 쌓는 것이기 때문에 인자가 필요없다.
print(a3)
print(a3.shape)

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1)
print(a1.shape)
print("---------------------------------------")
print(a2)
print(a2.shape)
print("---------------------------------------")
print("---------------------------------------")
a3 = np.dstack([a1, a2])
print(a3)
print(a3.shape)

In [7]:
a = np.random.randint(0, 10, (100, 200, 3)) # 100개의 테이블을 가졌고 200개의 행을 가졌고 3개의 열을 가진..
b = np.random.randint(0, 10, a.shape) # 같은 크기라면 이렇게 .shape로 써줘도 괜찮다!
c = np.random.randint(0, 10, a.shape)
print("---------------------------------------")
d = np.dstack([a, b, c])
print(d.shape)
print("---------------------------------------")
e = np.stack([a,b,c])
print(e.shape)
print("---------------------------------------")
f = np.stack([a,b,c], axis=1) # axis는 0일때 맽앞! 1씩 늘어날때마다 오른쪽으로 이동!
print(f.shape)

---------------------------------------
(100, 200, 9)
---------------------------------------
(3, 100, 200, 3)
---------------------------------------
(100, 3, 200, 3)


## (4) tile()
 - ?np.tile
 - np.tile(A, reps)

In [11]:
a = 1
b = np.array([0, 1])
c = np.array([[0, 1], [2, 3]])

In [25]:
### resp가 상수일경우(열 방향으로만 증식~~)
print(a)
print(np.tile(a, 3)) # 열방향으로 3개로 늘었다.

print("---------------------------------------")
print(b)
print(np.tile(b, 3)) # 열방향으로 3개로 늘었다

print("---------------------------------------")
print(c)
print(np.tile(c, 3)) # 열방향으로 3개로 늘었다


print("---------------------------------------")
print(c)
print(np.tile(c, (1, 3))) # 상수 3을 입력한 것가 같은 결과. 왜냐하면 행으로는 증식기준을 1로 잡아서 그대로이기 때문.

1
[1 1 1]
---------------------------------------
[0 1]
[0 1 0 1 0 1]
---------------------------------------
[[0 1]
 [2 3]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]
---------------------------------------
[[0 1]
 [2 3]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]


In [ ]:
### resp가 튜플일경우
print(a)
print(np.tile(a, (2, 3))) # 특정 값을 배열로 만들어준다. 단순한 1이던게 1로 이뤄진 2행 3열의 배열로 탄생

print("---------------------------------------")
print(b)
print(np.tile(b, (2, 3))) # b라는 덩어리를 하나로 생각하고 2행 3열로 증식시켰다.

print("---------------------------------------")
print(c)
print(np.tile(c, (2, 3))) # c라는 덩어리를 하나로 생각하고 마찬가지로 2행 3열로 증식시켰다.(타일을 붙여나가듯이)

### 배열 분할

### split() : 배열 분할

In [126]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, de, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, de, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


### vsplit() : 수직 분할, 1차원으로 분할

In [127]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


### hsplit() : 수평 분할, 2차원으로 분할

In [128]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


### dsplit() : 깊이 분할, 3차원으로 분할

In [129]:
a2 = np.arange(1,28).reshape(3,3,3)
print(a2)
b3, c3 = np.dsplit(a2, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 12.  Broadcasting

- http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html
- 규칙
    - 축의 길이가 같아야 한다.
    - 배열 중 하나의 길이가 1인 경우.

In [ ]:
# 1차원 배열로 0번 축에 대해 브로드캐스팅 p.602
# 2차원 배열의 1번 축에 대한 브로드캐스팅 p.603

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1])

print(a + b)

print("-----------------------------")


#a = np.array([1, 2, 3])
#b = np.array([1,2]) # 이건 안된다 
#print(a + b)

In [40]:
np.vstack([list(range(7)[i:i+3]) for i in range(5)]) # 아래의 문을 vstack으로 쌓은 것

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [39]:
[list(range(7)[i:i+3]) for i in range(5)] # range(7)[i:i+3] == 0~6까지의 범위를 i~i3으로 슬라이싱한거! 그걸 5번 반복!

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [51]:
x = np.vstack([list(range(7)[i:i+3]) for i in range(5)])
print(x)
print(x.shape)

print("-----------------------------")

y = np.arange(5)
print(y)
print(y.shape)

# print(x+y) # 안된다! x는 (5,3), y는 (5,)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
(5, 3)
-----------------------------
[0 1 2 3 4]
(5,)


In [61]:
y = np.arange(5)
print(y)
print(y.shape)

print("-----------------------------")

y = np.arange(5)[:, np.newaxis] # 1차원을 2차원으로 바꿨다. 축을 하나 새로 만들었다.
print(y)
print(y.shape)

print("-----------------------------")

z = np.arange(5)
print(z)
print(z.shape)
print("-----------------------------")
z1 = z.reshape(5, 1)
print(z.reshape(5, 1))
print(z1)
print(z1.shape)

print("-----------------------------")
print(x+y)                                       # 축을 맞췄더니 가능해졌다.
print(x+z1)

[0 1 2 3 4]
(5,)
-----------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
-----------------------------
[0 1 2 3 4]
(5,)
-----------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
-----------------------------
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


## 13. 차원 축소(dimension reduction) 연산

- 최대값/최소값 : max(), min(), argmax(), argmin()
- 대표값 : mean(0, sum(), median(), std(), var()
- 논리값 : all(), any()
- ...

In [65]:
# 최대값, 최소값 그 자체보다는 최대값이 있는 위치가 필요할 떄가 있다.

x = np.array([1, 3, 2, -3])

print(np.max(x))
print(np.argmax(x)) # 1 = 1번째 자리에 최대값이 있다
print(np.argmin(x)) # 3 = 3번째 자리에 최소값이 있다.

3
1
3


## 14. 기술 통계

- sum(), mean()
- max(), min()
- var(), std()
- len()
- median()
- percentile()
- ...




In [68]:
import scipy.stats

x = np.random.randn(20)
print(x)

scipy.stats.describe(x) # describe -> 길이, 최소값, 최대값, 평균, 편차??;; 첨도?? 등의 정보를 한번에 보여줌.

[ 0.09642071  0.00290325 -0.39102246  0.51755069  0.12898758  0.98987982
 -1.0939084  -0.19106362 -1.84474256 -0.87684618  0.9971941   0.51681887
  1.36341642  0.30740538  0.68409879 -0.04049159 -0.28199309 -0.46251093
  0.09415864 -0.50437079]


DescribeResult(nobs=20, minmax=(-1.8447425583586636, 1.3634164221103806), mean=0.0005942318328475915, variance=0.5827817808306999, skewness=-0.4213438689238421, kurtosis=0.1857111272146703)

## 15. 정렬


In [69]:
arr = np.array([[4,3,5,7],
                [1,12,11,9],
                [2,15,1,14]])

In [77]:
print(np.sort(arr)) # 행별로 정렬이 이루어진다
print("-----------------------------")
print(np.sort(arr, axis=0)) # 열별로 정렬이 이루어진다
print("-----------------------------")
print(np.sort(arr, axis=1)) # 행별로 정렬이 이루어진다
print("-----------------------------")


print(np.sort(arr, axis=0))
print("-----------------------------")
print(arr)                   # 원본은 그대로다! 따로 변수로 빼두고 저장한 것이 아니기에!
print("-----------------------------")
arr =  np.sort(arr)          # 정렬한 결과를 원본으로
print(arr)                   # 이제 행별로 정렬한 것이 원본이 되었다.


[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
-----------------------------
[[ 1  2  5  7]
 [ 1  4 11 12]
 [ 3  9 14 15]]
-----------------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
-----------------------------
[[ 1  2  5  7]
 [ 1  4 11 12]
 [ 3  9 14 15]]
-----------------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
-----------------------------
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [78]:
arr = np.array([[4,3,5,7],
                [1,12,11,9],
                [2,15,1,14]])

# 또 다른 방법

arr.sort()        # print가 아니라 함수를 불러온거라 바로 원본에 적용되었다.
print(arr)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [18]:
### resp가 튜플일경우
print(a)
print(np.tile(a, (2, 3))) # 특정 값을 배열로 만들어준다. 단순한 1이던게 1로 이뤄진 2행 3열의 배열로 탄생

print("---------------------------------------")
print(b)
print(np.tile(b, (2, 3))) # b라는 덩어리를 하나로 생각하고 2행 3열로 증식시켰다.

print("---------------------------------------")
print(c)
print(np.tile(c, (2, 3))) # c라는 덩어리를 하나로 생각하고 마찬가지로 2행 3열로 증식시켰다.(타일을 붙여나가듯이)

1
[[1 1 1]
 [1 1 1]]
---------------------------------------
[0 1]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]]
---------------------------------------
[[0 1]
 [2 3]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]


## 12.  Broadcasting

- http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html
- 규칙
    - 축의 길이가 같아야 한다.
    - 배열 중 하나의 길이가 1인 경우.

In [26]:
# 1차원 배열로 0번 축에 대해 브로드캐스팅 p.602
# 2차원 배열의 1번 축에 대한 브로드캐스팅 p.603

In [29]:
a = np.array([1, 2, 3])
b = np.array([1])

print(a + b)

print("-----------------------------")


#a = np.array([1, 2, 3])
#b = np.array([1,2]) # 이건 안된다 
#print(a + b)

[2 3 4]
-----------------------------


In [80]:
#### argsort()

arr = np.array([42, 38, 12, 25])

idx = np.argsort(arr)
print(arr[idx])
print(idx)

[12 25 38 42]
[2 3 1 0]


In [87]:
### 내림차순
print(ex[::-1])
print(arr[np.argsort(-arr)])

[9 8 7 6 5 4 3 2 1 0]
[42 38 25 12]


In [84]:
##### 슬라이싱 : 배열[시작위치 : 끝위치 : 간격]


ex = np.arange(10)

print(ex[:])
print(ex[::1])
print(ex[::2])
print(ex[::-1])
print(ex[::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]


## 16. 난수

- rand() : 0 ~ 1사이의 균일분포
- randn() : 정규분포
- randint() : 균일분포에서 정수

In [31]:
print(np.random.rand(10))
print("------------------")
print(np.random.rand(3, 5))

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678  0.33033482
 0.20464863 0.61927097 0.29965467 0.26682728]
------------------
[[0.62113383 0.52914209 0.13457995 0.51357812 0.18443987]
 [0.78533515 0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092 0.12715997]]


In [32]:
print(np.random.randint(10)) # 0부터 9까지의 난수 중에서 1개
print("------------------")
print(np.random.randint(11, 20)) # 11부터 19까지의 난수 중에서 1개
print(np.random.randint(11, 20, size=10)) # 11부터 19까지의 난수 중에서 10개
print(np.random.randint(11, 20, size=(2, 3))) # 11부터 19까지의 난수로 (2,3)배열을 만들라

2
------------------
15
[12 18 19 13 19 18 12 17 19 16]
[[14 11 11]
 [13 19 19]]


### (1) 재현성(난수 고정)

In [33]:
np.random.seed(5)

np.random.seed(2)

### (2) 데이터의 순서 바꾸기

In [34]:
x = np.arange(10)
print(x)

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 1 5 0 7 2 3 6 9 8]


### (3) 샘플링 : 복원(default), 비복원

In [106]:
print(np.random.choice(7, 5)) # 복원 # 뽑힌게 또 나올 수도 있다! # 0~7까지의 숫자 중에서 5번을 추출

[3 4 2 3 3]


In [110]:
print(np.random.choice(7, 5, replace=False)) # 비복원 # 뽑힌건 안나온다!

[5 4 6 0 2]


In [117]:
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])) # p=[, , , ]안에 확률을 합쳐서 1이 되도록

[3 3 3 2 2 3 3 3 3 2]


### 17. 정수형 데이터 카운팅

- unique()
- bincount()

In [131]:
arr = np.array(['a','b','b','c','a'])

# print(np.unique(arr))                            # 중복을 제거해줌
idx,cnt = np.unique(arr, return_counts=True)     # 중복된 갯수를 세숨

print(idx)
print(cnt)

['a' 'b' 'c']
[2 2 1]


In [119]:
print(len(arr))
print(np.unique(arr))
print(len(np.unique(arr)))

5
['a' 'b' 'c']
3


In [120]:
np.unique(arr, return_counts=True) # 앞쪽은 중복을 제거한 배열, 뒤는 행마다 몇개가 중복되어 있는지와 타입이 나옴

print(cnt)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

### (2) bincount()

- 발생하지 않은 사건에 대해서도 카운팅



In [124]:
arr = np.array([1, 1, 2, 2, 2, 3]) # 주사위 눈금이라고 가정

print(np.unique(arr, return_counts=True))
print(np.bincount(arr)) # 0은 1번 나왔고, 1은 2번 나왔고, 3은 1번 나왔다고 카운트해줌
print(np.bincount(arr, minlength=6)) # 안나온 값들은 0으로 채워서 나왔다.

(array([1, 2, 3]), array([2, 3, 1], dtype=int64))
[0 2 3 1]
[0 2 3 1 0 0]


### 배열 조회

In [40]:
def array_info(array):
    print(array) # 실제 배열의 값
    print("ndim:", array.ndim) # 배열이 몇차원인지
    print("shape:", array.shape) # 모양은 이렇게 생겼구나
    print("dtype:", array.dtype) # 어떤 데이터타입을 쓰는구나
    print("size:", array.size) # 엘레멘츠의 갯수
    print("itemsize:", array.itemsize) # 각 하나의 아이템이 가진 사이즈 byte
    print("nbytes:", array.nbytes) # 총 바이트 사이즈
    print("strides:", array.strides) # 다음 차원으로 넘어가기 위한 바이트 수

In [41]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [42]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [43]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


## 18. 실습

- 영화 평점 데이터
- https://grouplens.org/datasets/movielens/
- MovieLens 1M Dataset(ml-1m.zip (size: 6 MB, checksum)) 받기

In [3]:
file = np.loadtxt("C:\\kimhotak13\\Analysis\\data\\data\\ml-1m\\ratings.dat", delimiter="::", dtype=np.int64) # delimeter = 구분하는 방법

In [4]:
print(file)
print(file.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
(1000209, 4)


In [11]:
#### 첫행부터 20행까지 출력 # file = 2차원 배열
print(file[0:20])
print("------------------------------------")
print(file[:20,])
print("------------------------------------")
print(file[:20, :])
print("------------------------------------")

print("------------------------------------")
#### 21행부터 30행까지 userid와 movieid만 출력
print(file[21:31, 0:2])
print("------------------------------------")
print(file[21:31, [0, 1]]) # 만약에 뽑고자하는 데이터가 연속되지 않고 떨어져있는 경우!! 이런식으로 따로 지정
print("------------------------------------")
#### 전체 평점에 대한 평균
print(np.mean(file[:,[2]]))
print("------------------------------------")
print(np.mean(file[:,2]))
print("------------------------------------")
print(type(file[:,2]))
print("------------------------------------")
file[:,2].mean()
print("------------------------------------")
np.mean(file[:,2])

print("------------------------------------")
#### 사용자별로 평점 평균(10명만 출력)
print(np.mean(file[0,[2]]))



[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]]
------------------------------------
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1     

In [193]:
# 4. 사용자별로 평점 평균(10명만 출력) - 엄진성버전
print(file[:,2])

for i in range(1,11):               # i의 범위는 1~10 으로 지정해준다.
    idx = (file[:,0] == i)          # file[:,0] 을 전부 불러와서 사용자 ID(file[:,0])가 차례대로 1번~10번까지 맞는지 확인해주고
    rows = file[idx,2]              # 사용자 ID가 1~10과 일치하는 행에서 평점들의 데이터를 불러와준다.
    print(np.mean(rows))            # 그 데이터들의 평균을 구해준다.

[5 3 3 ... 5 4 4]
4.188679245283019
3.7131782945736433
3.9019607843137254
4.190476190476191
3.1464646464646466
3.9014084507042255
4.32258064516129
3.884892086330935
3.7358490566037736
4.114713216957606


In [21]:
# 4. 사용자별로 평점 평균(10명만 출력) - 엄진성버전
#print(file[0,2])
#usernum=file[:,[0]]
#print(usernum) # user ID 전체행
#for i in usernum <= 10:
#print(np.mean(file[i:i,[2]]))

user_id = np.unique(file[: , 0])
print(user_id.shape)

means = []# 1번 사용자의 평균, 2번 사용자의 평균, 3번 사용자의 평균, ...

for id in user_id:
    user = file[file[:, 0] == id, :] # numpy의 장점. 인덱스 안에 조건문이나 리스트 컴프리헨션도 넣을 수 있다. 집중
    means.append([id, user[:, 2].mean()]) # append로 추가해야 리스트 안에 또 리스트로 나온다. extend 노노
    
print("결과 : ", means[:10])
    


(6040,)
결과 :  [[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606]]
-*-*-*-***------------------------------------------


In [34]:
# 4. 사용자별로 평점 평균(10명만 출력) # 리스트 컴프리헨션

file[file[:, 0] == 1].mean(axis=0)[2]

result = [[id, file[file[:, 0] == id].mean(axis=0)[2]] for id in range(1,11)]

print("결과 : ", result)


결과 :  [[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606]]


In [37]:
##### 결과값을 numpy를 이용하여 저장

np.savetxt("C:\\kimhotak13\\Analysis\\data\\data\\ml-1m\\ratings_mean.csv", means, delimiter=",", fmt="%.2f") 
# 원래는 아래처럼 배열로 해줘야함 # 리스트 형식은 기본적으로 배열을 안써도 되도록 패치한듯하다고함
np.savetxt("C:\\kimhotak13\\Analysis\\data\\data\\ml-1m\\ratings_mean.csv", np.array(means), delimiter=",", fmt="%.2f")